spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
auth:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080

    default-redirect-uri: http://localhost:8080
